version: 3
endpoint: http://127.0.0.1:8082
admin_secret: softuniAngularAdminSecret
metadata_directory: hasura/metadata
migrations_directory: hasura/migrations
actions:
  kind: synchronous
  handler_webhook_baseurl: http://127.0.0.1:3000
